GET http://localhost:3001/foods HTTP/1.1
Content-Type: application/json

###

POST  http://localhost:3001/foods HTTP/1.1
Content-Type: application/json

{
    "dish": "Calamari"
}

###

PUT http://localhost:3001/foods/1 HTTP/1.1
Content-Type: application/json

{
    "dish":"Curry"
}

###
DELETE http://localhost:3001/foods/2 HTTP/1.1
Content-Type: application/json